# Generated by Django 4.2.3 on 2023-07-12 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demodj', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'student', 'verbose_name_plural': 'students'},
        ),
    ]
